import { DurableObject } from "cloudflare:workers";

const SUITS = ["♠","♥","♦","♣"];
const RANKS = ["A","2","3","4","5","6","7","8","9","10","J","Q","K"];
const EMOJIS = ["😎","🦊","🐼","🐱","🐯","🦄","🐸","🐵","🐰","🐻","🐨","🐙","🦋","🌸","🍓","🌙","⭐","🔥","👻","💎","🍀","⚡","🐲"];
const BOARD=[["X","2♠","3♠","4♠","5♠","6♠","7♠","8♠","9♠","X"],["6♣","5♣","4♣","3♣","2♣","A♥","K♥","Q♥","10♥","10♠"],["7♣","A♠","2♦","3♦","4♦","5♦","6♦","7♦","9♥","Q♠"],["8♣","K♠","6♣","5♣","4♣","3♣","2♣","8♦","8♥","K♠"],["9♣","Q♠","7♣","6♥","5♥","4♥","A♥","9♦","7♥","A♠"],["10♣","10♠","8♣","7♥","2♥","3♥","K♥","10♦","6♥","2♦"],["Q♣","9♠","9♣","8♥","9♥","10♥","Q♥","Q♦","5♥","3♦"],["K♣","8♠","10♣","Q♣","K♣","A♣","A♦","K♦","4♥","4♦"],["A♣","7♠","6♠","5♠","4♠","3♠","2♠","2♥","3♥","5♦"],["X","A♦","K♦","Q♦","10♦","9♦","8♦","7♦","6♦","X"]];
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function makeDeck(){const d=[];for(let copy=0;copy<2;copy++)for(const suit of SUITS)for(const rank of RANKS)d.push({rank,suit,key:rank+suit});return shuffle(d)}
function isTwoEyed(c){return c?.rank==="J"&&(c.suit==="♣"||c.suit==="♦")}
function isOneEyed(c){return c?.rank==="J"&&(c.suit==="♠"||c.suit==="♥")}
function cleanName(n){return String(n||"").replace(/[^\p{L}\p{N} _-]/gu,"").trim().slice(0,20)}
function cleanEmoji(e){return EMOJIS.includes(e)?e:"😎"}
function validRoom(r){return /^[A-Z0-9]{4,8}$/.test(r)}
function handSize(n){return n===2?7:n<=5?6:5}
function clampTimer(n){n=Number(n);return Number.isFinite(n)?Math.max(10,Math.min(120,Math.round(n))):60}
function randomizeTeams(players){const names=players.length===2?["Blue","Red"]:players.length===3?["Blue","Green","Red"]:players.length===4?["Blue","Red"]:["Blue","Green","Red"],teams=names.map((name,i)=>({id:`team-${i}`,name,color:name.toLowerCase()})),slots=[];while(slots.length<players.length)slots.push(...names);shuffle(slots);players.forEach((p,i)=>{const t=teams.find(x=>x.name===slots[i]);Object.assign(p,{teamId:t.id,teamName:t.name,teamColor:t.color,tokenKey:t.id})});return{players,teams}}
function getSequences(board,teamId){const dirs=[[1,0],[0,1],[1,1],[1,-1]],out=[],occ=(r,c)=>r>=0&&r<10&&c>=0&&c<10&&(board[r][c]===teamId||board[r][c]==="corner");for(let r=0;r<10;r++)for(let c=0;c<10;c++)for(const[dr,dc]of dirs){const pr=r-dr,pc=c-dc;if(occ(pr,pc)||!occ(r,c))continue;const run=[];let rr=r,cc=c;while(occ(rr,cc)){run.push(`${rr},${cc}`);rr+=dr;cc+=dc}for(let k=0;k<Math.floor((run.length-1)/4);k++)out.push(run.slice(k*4,k*4+5))}return out}
function isProtectedChip(board,r,c,teamId){return getSequences(board,teamId).some(seq=>seq.includes(`${r},${c}`))}
function createGame(players){const deck=makeDeck(),hands=players.map(()=>[]),size=handSize(players.length);for(let round=0;round<size;round++)for(let i=0;i<players.length;i++)if(deck.length)hands[i].push(deck.pop());const timers=players.map(p=>p.timerSeconds||60);return{status:"playing",board:BOARD.map(row=>row.map(v=>v==="X"?"corner":null)),deck,discard:players.map(()=>[]),hands,current:0,winner:null,winningCells:[],sequencesToWin:2,timerSeconds:timers,remainingSeconds:[...timers],lastTickAt:Date.now(),paused:false,pendingMove:null,teams:players.map(p=>({id:p.teamId,name:p.teamName,color:p.teamColor})),lastAutoPlay:null}}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==="/"){const res=await env.ASSETS.fetch(new Request(new URL("/index.html",request.url),request));if(!res.ok)return res;const html=await res.text();const headers=new Headers(res.headers);headers.set("content-type","text/html; charset=UTF-8");const decorated=html.replace("</head>","<link rel=\"stylesheet\" href=\"/premium-ui.css\"></head>").replace("</body>","<script src=\"/premium-ui.js\" defer></script></body>");return new Response(decorated,{status:res.status,headers})}if(url.pathname==="/health")return new Response("ok");if(url.pathname.startsWith("/ws/")){if(request.headers.get("Upgrade")!=="websocket")return new Response("Expected WebSocket",{status:426});const room=url.pathname.slice(4).toUpperCase();if(!validRoom(room))return new Response("Invalid room code",{status:400});return env.GAME_ROOM.get(env.GAME_ROOM.idFromName(room)).fetch(request)}return new Response("Not found",{status:404})}};
export class GameRoom extends DurableObject{
constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env}
async load(){return await this.ctx.storage.get("state")||{status:"lobby",board:null,deck:[],discard:[],hands:[],current:0,winner:null,players:[],spectators:[],teams:[],pendingMove:null,hostId:null}}
async save(state){await this.ctx.storage.put("state",state)}
async ensureAlarm(){if(await this.ctx.storage.getAlarm()==null)await this.ctx.storage.setAlarm(Date.now()+1000)}
async scheduleTimer(){await this.ctx.storage.setAlarm(Date.now()+1000)}
async fetch(request){const url=new URL(request.url),name=cleanName(url.searchParams.get("name")),pid=String(url.searchParams.get("pid")||"").slice(0,80),spectator=url.searchParams.get("spectator")==="1",emoji=cleanEmoji(url.searchParams.get("emoji"));if(!name||!pid)return new Response("Name and player id are required",{status:400});const pair=new WebSocketPair(),client=pair[0],server=pair[1];this.ctx.acceptWebSocket(server);const state=await this.load();
if(spectator){server.serializeAttachment({pid,spectator:true});const s=(state.spectators||[]).find(x=>x.id===pid);if(s){s.name=name;s.emoji=emoji;s.connected=true}else state.spectators=[...(state.spectators||[]),{id:pid,name,emoji,connected:true}];await this.save(state);await this.broadcastState();return new Response(null,{status:101,webSocket:client})}
let effectivePid=pid;let player=state.players.find(p=>p.id===pid);if(player&&player.connected&&player.name.toLowerCase()!==name.toLowerCase()){effectivePid=`${pid}:${crypto.randomUUID()}`;player=null}server.serializeAttachment({pid:effectivePid,spectator:false});if(!player){if(state.status!=="lobby"){server.send(JSON.stringify({type:"error",message:"This game has already started. Join as a spectator instead."}));server.close(1008,"Game started");return new Response(null,{status:101,webSocket:client})}if(state.players.length>=12){server.send(JSON.stringify({type:"error",message:"This room is full."}));server.close(1008,"Room full");return new Response(null,{status:101,webSocket:client})}player={id:effectivePid,name,emoji,teamId:null,teamName:null,teamColor:null,connected:true,timerSeconds:60};state.players.push(player);if(!state.hostId)state.hostId=effectivePid}else{player.name=name;player.emoji=emoji;player.connected=true}await this.save(state);await this.broadcastState();return new Response(null,{status:101,webSocket:client})}
async webSocketMessage(ws,message){let data;try{data=JSON.parse(message)}catch{return}const a=ws.deserializeAttachment(),pid=a?.pid,isSpec=!!a?.spectator,state=await this.load(),i=state.players.findIndex(p=>p.id===pid);if(isSpec||i<0)return;
if(data.type==="set_timer"){if(pid!==state.hostId||state.status!=="lobby")return;const seconds=clampTimer(data.seconds);state.players.forEach(p=>p.timerSeconds=seconds);await this.save(state);return this.broadcastState()}
if(data.type==="start"){if(pid!==state.hostId||state.players.length<2||state.status!=="lobby")return;const randomized=randomizeTeams(state.players);state.players=randomized.players;state.teams=randomized.teams;Object.assign(state,createGame(state.players));await this.save(state);await this.ensureAlarm();return this.broadcastState()}
if(data.type==="pause"){if(pid!==state.hostId||state.status!=="playing")return;state.paused=!state.paused;state.lastTickAt=Date.now();if(state.paused)await this.ctx.storage.deleteAlarm();else await this.scheduleTimer();await this.save(state);return this.broadcastState()}
if(data.type==="end_turn"){if(pid!==state.hostId||state.status!=="playing"||state.paused)return;return this.finishOrAutoFinish(state,"host")}
if(data.type==="finish_turn"){if(state.status!=="playing"||state.paused||state.current!==i)return;return this.finishStagedTurn(state,i)}
if(data.type==="undo_move"){if(state.status!=="playing"||state.paused||state.current!==i)return;return this.undoMove(state,i)}
if(data.type==="tick")return;
if(data.type==="stage_play")return this.stagePlay(state,i,data);
if(data.type==="reset"&&pid===state.hostId){await this.ctx.storage.deleteAlarm();state.status="lobby";state.board=null;state.deck=[];state.discard=[];state.hands=[];state.current=0;state.winner=null;state.winningCells=[];state.paused=false;state.pendingMove=null;state.lastAutoPlay=null;state.players.forEach(p=>{p.teamId=null;p.teamName=null;p.teamColor=null});await this.save(state);return this.broadcastState()}}
async alarm(){const state=await this.load();if(state.status!=="playing"||state.paused){await this.ctx.storage.deleteAlarm();return}const now=Date.now(),elapsed=Math.floor((now-(state.lastTickAt||now))/1000);if(elapsed>0){state.lastTickAt=now;const i=state.current;state.remainingSeconds[i]=Math.max(0,(state.remainingSeconds[i]??state.timerSeconds[i]??60)-elapsed);if(state.remainingSeconds[i]<=0){await this.finishOrAutoFinish(state,"timer");return}await this.save(state);await this.broadcastState()}await this.scheduleTimer()}
async stagePlay(state,i,d){if(state.status!=="playing"||state.paused||state.current!==i||state.pendingMove)return;const hi=Number.isInteger(d.handIndex)?d.handIndex:-1,r=Number.isInteger(d.r)?d.r:-1,c=Number.isInteger(d.c)?d.c:-1,hand=state.hands[i]||[],card=hand[hi];if(!card||r<0||r>=10||c<0||c>=10||BOARD[r][c]==="X")return;const player=state.players[i],previous=state.board[r][c];if(isOneEyed(card)){if(!previous||previous==="corner"||previous===player.teamId||isProtectedChip(state.board,r,c,previous))return;state.board[r][c]=null}else{if(previous||(!isTwoEyed(card)&&BOARD[r][c]!==card.key))return;state.board[r][c]=player.teamId}state.pendingMove={playerIndex:i,handIndex:hi,r,c,previous,cardKey:card.key};await this.save(state);await this.broadcastState()}
async undoMove(state,i){const p=state.pendingMove;if(!p||p.playerIndex!==i)return;state.board[p.r][p.c]=p.previous;state.pendingMove=null;await this.save(state);await this.broadcastState()}
async finishStagedTurn(state,i){const p=state.pendingMove;if(!p||p.playerIndex!==i)return;const hand=state.hands[i]||[],card=hand[p.handIndex],player=state.players[i];if(!card||card.key!==p.cardKey){state.pendingMove=null;await this.save(state);return this.broadcastState()}state.discard[i].push(card);hand.splice(p.handIndex,1);if(state.deck.length>0)hand.push(state.deck.pop());state.pendingMove=null;const seq=getSequences(state.board,player.teamId);if(seq.length>=state.sequencesToWin){state.status="finished";state.winner=player.id;state.winningCells=[...new Set(seq.flat())];await this.ctx.storage.deleteAlarm()}else{state.current=(state.current+1)%state.players.length;state.remainingSeconds[state.current]=state.timerSeconds[state.current]}state.lastTickAt=Date.now();await this.save(state);if(state.status==="playing")await this.scheduleTimer();await this.broadcastState()}
async finishOrAutoFinish(state,reason){if(state.status!=="playing"||state.paused)return;if(state.pendingMove)return this.finishStagedTurn(state,state.pendingMove.playerIndex);return this.autoPlay(state,state.current,reason)}
async autoPlay(state,i,reason){if(state.status!=="playing")return;const player=state.players[i],hand=state.hands[i]||[],m=this.chooseMove(state,i);if(m){const card=hand[m.handIndex];if(m.kind==="remove")state.board[m.r][m.c]=null;else state.board[m.r][m.c]=player.teamId;state.discard[i].push(card);hand.splice(m.handIndex,1);if(state.deck.length>0)hand.push(state.deck.pop());const seq=getSequences(state.board,player.teamId);if(seq.length>=2){state.status="finished";state.winner=player.id;state.winningCells=[...new Set(seq.flat())];await this.ctx.storage.deleteAlarm()}}if(state.status==="playing"){state.current=(state.current+1)%state.players.length;state.remainingSeconds[state.current]=state.timerSeconds[state.current]}state.lastTickAt=Date.now();state.lastAutoPlay={playerId:player.id,reason,summary:m?.summary||"Auto-finish found no legal move."};await this.save(state);if(state.status==="playing")await this.scheduleTimer();await this.broadcastState()}
chooseMove(state,i){const player=state.players[i],team=player.teamId,hand=state.hands[i]||[],candidates=[];const place=(r,c,hi,summary)=>{const copy=state.board.map(row=>row.slice()),before=getSequences(state.board,team).length;copy[r][c]=team;const after=getSequences(copy,team).length;candidates.push({kind:"place",handIndex:hi,r,c,score:after*1000+(after>before?5000:0),summary:after>before?"Auto-finish created a sequence.":summary})};hand.forEach((card,hi)=>{if(isTwoEyed(card)){for(let r=0;r<10;r++)for(let c=0;c<10;c++)if(state.board[r][c]===null&&BOARD[r][c]!=="X")place(r,c,hi,"Auto-finish used a wild Jack.")}else if(!isOneEyed(card)){for(let r=0;r<10;r++)for(let c=0;c<10;c++)if(state.board[r][c]===null&&BOARD[r][c]===card.key)place(r,c,hi,`Auto-finish played ${card.rank}${card.suit}.`)}});hand.forEach((card,hi)=>{if(!isOneEyed(card))return;for(let r=0;r<10;r++)for(let c=0;c<10;c++){const token=state.board[r][c];if(!token||token==="corner"||token===team||isProtectedChip(state.board,r,c,token))continue;const before=getSequences(state.board,token).length,copy=state.board.map(row=>row.slice());copy[r][c]=null;const after=getSequences(copy,token).length;candidates.push({kind:"remove",handIndex:hi,r,c,score:(before-after)*1200,summary:before>after?"Auto-finish broke an opponent threat.":"Auto-finish used a removal Jack."})}});candidates.sort((a,b)=>b.score-a.score);return candidates[0]||null}
async broadcastState(){const state=await this.load();for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment(),pid=a?.pid,spec=!!a?.spectator,me=state.players.findIndex(p=>p.id===pid);const payload={type:"state",status:state.status,players:state.players,current:state.current,currentPlayerId:state.players[state.current]?.id||null,isHost:pid===state.hostId,hostId:state.hostId,board:state.board,winner:state.winner,winningCells:state.winningCells,sequencesToWin:2,me,isSpectator:spec,hand:!spec&&me>=0?[...(state.hands[me]||[])]:[],discards:state.discard,deckCount:state.deck.length,timerSeconds:state.timerSeconds||[],remainingSeconds:state.remainingSeconds||[],teams:state.teams||[],paused:!!state.paused,pendingMove:state.pendingMove?{playerId:state.players[state.pendingMove.playerIndex]?.id||null,r:state.pendingMove.r,c:state.pendingMove.c}:null,lastAutoPlay:state.lastAutoPlay||null,spectators:state.spectators||[]};try{ws.send(JSON.stringify(payload))}catch{}}}
async webSocketClose(ws){const a=ws.deserializeAttachment(),state=await this.load(),p=state.players.find(x=>x.id===a?.pid),s=(state.spectators||[]).find(x=>x.id===a?.pid);if(p)p.connected=false;if(s)s.connected=false;await this.save(state);await this.broadcastState()}
async webSocketError(ws){await this.webSocketClose(ws)}
}
