import { DurableObject } from "cloudflare:workers";

const SUITS=["♠","♥","♦","♣"],RANKS=["A","2","3","4","5","6","7","8","9","10","J","Q","K"];
const BOARD=[["X","2♠","3♠","4♠","5♠","6♠","7♠","8♠","9♠","X"],["6♣","5♣","4♣","3♣","2♣","A♥","K♥","Q♥","10♥","10♠"],["7♣","A♠","2♦","3♦","4♦","5♦","6♦","7♦","9♥","Q♠"],["8♣","K♠","6♣","5♣","4♣","3♣","2♣","8♦","8♥","K♠"],["9♣","Q♠","7♣","6♥","5♥","4♥","A♥","9♦","7♥","A♠"],["10♣","10♠","8♣","7♥","2♥","3♥","K♥","10♦","6♥","2♦"],["Q♣","9♠","9♣","8♥","9♥","10♥","Q♥","Q♦","5♥","3♦"],["K♣","8♠","10♣","Q♣","K♣","A♣","A♦","K♦","4♥","4♦"],["A♣","7♠","6♠","5♠","4♠","3♠","2♠","2♥","3♥","5♦"],["X","A♦","K♦","Q♦","10♦","9♦","8♦","7♦","6♦","X"]];
const EMOJIS=["😎","🦊","🐼","🐱","🐯","🦄","🐸","🐵","🐰","🐻","🐨","🐙","🦋","🌸","🍓","🌙","⭐","🔥","👻","💎","🍀","⚡","🐨","🐲"];
function playerLimit(){return 12}
function randomizeTeams(players){const n=players.length,names=n===2?["Blue","Red"]:n===3?["Blue","Green","Red"]:n===4?["Blue","Red"]:["Blue","Green","Red"],teams=names.map((name,i)=>({id:`team-${i}`,name,color:name.toLowerCase()})),slots=[];while(slots.length<n)slots.push(...names);slots.length=n;for(let i=slots.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[slots[i],slots[j]]=[slots[j],slots[i]]}players.forEach((p,i)=>{const t=teams.find(t=>t.name===slots[i]);Object.assign(p,{teamId:t.id,teamName:t.name,teamColor:t.color,tokenKey:t.id})});return{players,teams}}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}}
function makeDeck(){const d=[];for(let n=0;n<2;n++)for(const suit of SUITS)for(const rank of RANKS)d.push({rank,suit,key:rank+suit});shuffle(d);return d}
function isTwoEyed(c){return c?.rank==="J"&&(c.suit==="♣"||c.suit==="♦")}
function isOneEyed(c){return c?.rank==="J"&&(c.suit==="♠"||c.suit==="♥")}
function cleanName(n){return String(n||"").replace(/[^\p{L}\p{N} _-]/gu,"").trim().slice(0,20)}
function cleanEmoji(e){return EMOJIS.includes(e)?e:"😎"}
function validRoom(r){return /^[A-Z0-9]{4,8}$/.test(r)}
function handSize(n){return n===2?7:n<=5?6:5}
function clampTimer(n){n=Number(n);return Number.isFinite(n)?Math.max(10,Math.min(120,Math.round(n))):60}
// Corners are permanent wild spaces. No physical chip is ever placed there.
// A straight run of nine counts as exactly two five-position sequences.
function getSequences(g,chip){const dirs=[[1,0],[0,1],[1,1],[1,-1]],out=[],occ=(r,c)=>r>=0&&r<10&&c>=0&&c<10&&(g[r][c]===chip||g[r][c]==="corner");for(let r=0;r<10;r++)for(let c=0;c<10;c++)for(const[dr,dc]of dirs){const pr=r-dr,pc=c-dc;if(occ(pr,pc)||!occ(r,c))continue;const run=[];let rr=r,cc=c;while(occ(rr,cc)){run.push(`${rr},${cc}`);rr+=dr;cc+=dc}if(run.length>=5)for(let k=0;k<Math.floor((run.length-1)/4);k++)out.push(run.slice(k*4,k*4+5))}return out}
function isProtectedChip(g,r,c,chip){return getSequences(g,chip).some(s=>s.includes(`${r},${c}`))}
function freshGame(players){const deck=makeDeck(),hands=players.map(()=>[]),hs=handSize(players.length);for(let i=0;i<hs;i++)for(let p=0;p<players.length;p++)if(deck.length)hands[p].push(deck.pop());const timers=players.map(p=>p.timerSeconds||60);return{status:"playing",board:BOARD.map(row=>row.map(v=>v==="X"?"corner":null)),deck,discard:players.map(()=>[]),hands,current:0,winner:null,winningCells:[],sequencesToWin:2,timerSeconds:timers,remainingSeconds:[...timers],lastTickAt:Date.now(),paused:false,pendingMove:null,teams:players.map(p=>({id:p.teamId,name:p.teamName,color:p.teamColor})),lastAutoPlay:null}}

export default{async fetch(request,env){const u=new URL(request.url);if(u.pathname==="/")return env.ASSETS.fetch(new Request(new URL("/index.html",request.url),request));if(u.pathname==="/health")return new Response("ok");if(u.pathname.startsWith("/ws/")){if(request.headers.get("Upgrade")!=="websocket")return new Response("Expected WebSocket",{status:426});const room=u.pathname.slice(4).toUpperCase();if(!validRoom(room))return new Response("Invalid room code",{status:400});return env.GAME_ROOM.get(env.GAME_ROOM.idFromName(room)).fetch(request)}return new Response("Not found",{status:404})}};

export class GameRoom extends DurableObject{
 constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env}
 async load(){return await this.ctx.storage.get("state")||{status:"lobby",board:null,deck:[],discard:[],hands:[],current:0,winner:null,players:[],spectators:[],teams:[],pendingMove:null,hostId:null}}
 async save(s){await this.ctx.storage.put("state",s)}
 async fetch(request){const u=new URL(request.url),name=cleanName(u.searchParams.get("name")),pid=String(u.searchParams.get("pid")||"").slice(0,80),spectator=u.searchParams.get("spectator")==="1",emoji=cleanEmoji(u.searchParams.get("emoji"));if(!name||!pid)return new Response("Name and player id are required",{status:400});const pair=new WebSocketPair(),client=pair[0],server=pair[1];this.ctx.acceptWebSocket(server);server.serializeAttachment({pid,spectator});const state=await this.load();
  if(spectator){const s=(state.spectators||[]).find(x=>x.id===pid);if(s){s.name=name;s.emoji=emoji;s.connected=true}else state.spectators=[...(state.spectators||[]),{id:pid,name,emoji,connected:true}];await this.save(state);await this.broadcastState();return new Response(null,{status:101,webSocket:client})}
  let p=state.players.find(x=>x.id===pid);if(!p){if(state.status!=="lobby"){server.send(JSON.stringify({type:"error",message:"This game has already started. Join as a spectator instead."}));server.close(1008,"Game started");return new Response(null,{status:101,webSocket:client})}if(state.players.length>=playerLimit()){server.send(JSON.stringify({type:"error",message:"This room is full."}));server.close(1008,"Room full");return new Response(null,{status:101,webSocket:client})}p={id:pid,name,emoji,teamId:null,teamName:null,teamColor:null,connected:true,timerSeconds:60};state.players.push(p);if(!state.hostId)state.hostId=pid}else{p.name=name;p.emoji=emoji;p.connected=true}
  await this.save(state);await this.broadcastState();return new Response(null,{status:101,webSocket:client})}
 async webSocketMessage(ws,message){let d;try{d=JSON.parse(message)}catch{return}const a=ws.deserializeAttachment(),pid=a?.pid,isSpec=!!a?.spectator,state=await this.load(),i=state.players.findIndex(p=>p.id===pid);if(isSpec||i<0)return;
  if(d.type==="set_timer"){if(pid!==state.hostId||state.status!=="lobby")return;const sec=clampTimer(d.seconds);state.players.forEach(p=>p.timerSeconds=sec);await this.save(state);return this.broadcastState()}
  if(d.type==="start"){if(pid!==state.hostId||state.players.length<2||state.players.length>12||state.status!=="lobby")return;const t=randomizeTeams(state.players);state.players=t.players;state.teams=t.teams;Object.assign(state,freshGame(state.players));await this.save(state);return this.broadcastState()}
  if(d.type==="pause"){if(pid!==state.hostId||state.status!=="playing")return;state.paused=!state.paused;state.lastTickAt=Date.now();await this.save(state);return this.broadcastState()}
  if(d.type==="end_turn"){if(pid!==state.hostId||state.status!=="playing"||state.paused)return;return this.finishOrAutoFinishCurrentTurn(state,"host")}
  if(d.type==="finish_turn"){if(state.status!=="playing"||state.paused||state.current!==i)return;return this.finishStagedTurn(state,i)}
  if(d.type==="undo_move"){if(state.status!=="playing"||state.paused||state.current!==i)return;return this.undoStagedMove(state,i)}
  if(d.type==="tick")return this.handleTick(state)
  if(d.type==="stage_play")return this.stageMove(state,i,d)
  if(d.type==="reset"&&pid===state.hostId){state.status="lobby";state.board=null;state.deck=[];state.discard=[];state.hands=[];state.current=0;state.winner=null;state.winningCells=[];state.paused=false;state.pendingMove=null;state.lastAutoPlay=null;state.players.forEach(p=>{p.teamId=null;p.teamName=null;p.teamColor=null});await this.save(state);return this.broadcastState()}}
 async stageMove(state,i,d){if(state.status!=="playing"||state.paused||state.current!==i||state.pendingMove)return;const hi=Number.isInteger(d.handIndex)?d.handIndex:-1,r=Number.isInteger(d.r)?d.r:-1,c=Number.isInteger(d.c)?d.c:-1,hand=state.hands[i]||[],card=hand[hi];if(!card||r<0||r>=10||c<0||c>=10||BOARD[r][c]==="X")return;const player=state.players[i],previous=state.board[r][c];if(isOneEyed(card)){if(!previous||previous==="corner"||previous===player.teamId||isProtectedChip(state.board,r,c,previous))return;state.board[r][c]=null}else{if(previous||(!isTwoEyed(card)&&BOARD[r][c]!==card.key))return;state.board[r][c]=player.teamId}state.pendingMove={playerIndex:i,handIndex:hi,r,c,previous,cardKey:card.key};await this.save(state);await this.broadcastState()}
 async undoStagedMove(state,i){const p=state.pendingMove;if(!p||p.playerIndex!==i)return;state.board[p.r][p.c]=p.previous;state.pendingMove=null;await this.save(state);await this.broadcastState()}
 async finishStagedTurn(state,i){const p=state.pendingMove;if(!p||p.playerIndex!==i)return;const hand=state.hands[i]||[],card=hand[p.handIndex],player=state.players[i];if(!card||card.key!==p.cardKey){state.pendingMove=null;await this.save(state);return}state.discard[i].push(card);hand.splice(p.handIndex,1);if(state.deck.length)hand.push(state.deck.pop());state.pendingMove=null;const seq=getSequences(state.board,player.teamId);if(seq.length>=2){state.status="finished";state.winner=player.id;state.winningCells=[...new Set(seq.flat())]}else{state.current=(state.current+1)%state.players.length;state.remainingSeconds[state.current]=state.timerSeconds[state.current]}state.lastTickAt=Date.now();await this.save(state);await this.broadcastState()}
 async finishOrAutoFinishCurrentTurn(state,reason){if(state.status!=="playing"||state.paused)return;if(state.pendingMove)return this.finishStagedTurn(state,state.pendingMove.playerIndex);return this.autoPlayTurn(state,state.current,reason)}
 async handleTick(state){if(state.status!=="playing"||state.paused)return;const now=Date.now(),elapsed=Math.floor((now-(state.lastTickAt||now))/1000);if(elapsed<=0)return;state.lastTickAt=now;const i=state.current;state.remainingSeconds[i]=Math.max(0,(state.remainingSeconds[i]??state.timerSeconds[i]??60)-elapsed);if(state.remainingSeconds[i]<=0)return this.finishOrAutoFinishCurrentTurn(state,"timer");await this.save(state);await this.broadcastState()}
 async autoPlayTurn(state,i,reason){if(state.status!=="playing")return;const player=state.players[i],hand=state.hands[i]||[],move=this.chooseStrategicMove(state,i);if(move){const card=hand[move.handIndex];if(move.kind==="remove")state.board[move.r][move.c]=null;else state.board[move.r][move.c]=player.teamId;state.discard[i].push(card);hand.splice(move.handIndex,1);if(state.deck.length)hand.push(state.deck.pop());const seq=getSequences(state.board,player.teamId);if(seq.length>=2){state.status="finished";state.winner=player.id;state.winningCells=[...new Set(seq.flat())]}}if(state.status==="playing"){state.current=(state.current+1)%state.players.length;state.remainingSeconds[state.current]=state.timerSeconds[state.current]}state.lastTickAt=Date.now();state.lastAutoPlay={playerId:player.id,reason,summary:move?.summary||"Auto-finish found no legal move."};await this.save(state);await this.broadcastState()}
 chooseStrategicMove(state,i){const player=state.players[i],team=player.teamId,hand=state.hands[i]||[],c=[];const place=(r,col,hi,summary)=>{const copy=state.board.map(x=>x.slice()),before=getSequences(state.board,team).length;copy[r][col]=team;const after=getSequences(copy,team).length;c.push({kind:"place",handIndex:hi,r,c:col,score:after*1000+(after>before?5000:0),summary:after>before?"Auto-finish created a sequence.":summary})};hand.forEach((card,hi)=>{if(isTwoEyed(card)){for(let r=0;r<10;r++)for(let col=0;col<10;col++)if(state.board[r][col]===null&&BOARD[r][col]!=="X")place(r,col,hi,"Auto-finish used a wild Jack offensively.")}else if(!isOneEyed(card)){for(let r=0;r<10;r++)for(let col=0;col<10;col++)if(state.board[r][col]===null&&BOARD[r][col]===card.key)place(r,col,hi,`Auto-finish played ${card.rank}${card.suit}.`)}});hand.forEach((card,hi)=>{if(!isOneEyed(card))return;for(let r=0;r<10;r++)for(let col=0;col<10;col++){const token=state.board[r][col];if(!token||token==="corner"||token===team||isProtectedChip(state.board,r,col,token))continue;const before=getSequences(state.board,token).length,copy=state.board.map(x=>x.slice());copy[r][col]=null;const after=getSequences(copy,token).length;c.push({kind:"remove",handIndex:hi,r,c:col,score:(before-after)*1200,summary:before>after?"Auto-finish broke a threat.":"Auto-finish used a removal Jack."})}});c.sort((a,b)=>b.score-a.score);return c[0]||null}
 async sendToPlayer(pid,payload){for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment();if(a?.pid===pid)try{ws.send(JSON.stringify(payload))}catch{}}}
 async broadcastState(){const s=await this.load();for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment(),pid=a?.pid,spec=!!a?.spectator,me=s.players.findIndex(p=>p.id===pid);try{ws.send(JSON.stringify({type:"state",status:s.status,players:s.players,current:s.current,currentPlayerId:s.players[s.current]?.id||null,isHost:pid===s.hostId,hostId:s.hostId,board:s.board,winner:s.winner,winningCells:s.winningCells,sequencesToWin:2,me,isSpectator:spec,hand:!spec&&me>=0?s.hands[me]:[],discards:s.discard,deckCount:s.deck.length,timerSeconds:s.timerSeconds||[],remainingSeconds:s.remainingSeconds||[],teams:s.teams||[],paused:!!s.paused,pendingMove:s.pendingMove?{playerId:s.players[s.pendingMove.playerIndex]?.id||null,r:s.pendingMove.r,c:s.pendingMove.c}:null,lastAutoPlay:s.lastAutoPlay||null,spectators:s.spectators||[]}))}catch{}}}
 async webSocketClose(ws){const a=ws.deserializeAttachment(),s=await this.load(),p=s.players.find(x=>x.id===a?.pid),sp=(s.spectators||[]).find(x=>x.id===a?.pid);if(p)p.connected=false;if(sp)sp.connected=false;await this.save(s);await this.broadcastState()}
 async webSocketError(ws){await this.webSocketClose(ws)}
}
